# Generated by Django 4.0.5 on 2022-06-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technologies',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
